std = "roblox"

[lints]
shadowing = "warn"
unused_variable = "warn"

[globals]
workspace = { read_only = true }
game      = { read_only = true }
script    = { read_only = true }
describe  = { read_only = true }
it        = { read_only = true }
expect    = { read_only = true }
