# StyLua config for Luau (Roblox)
syntax = "luau"            # StyLua >= 2.0 uses this
column_width = 110
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
